/// cart
export const ADD_TO_CART_LOADING = "ADD_TO_CART_LOADING";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
