// create orders
export const NEW_ORDER_LOADING = "NEW_ORDER_LOADING";
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
export const NEW_ORDER_ERROR = "NEW_ORDER_ERROR";

// get orders
export const GET_ORDER_LOADING = "GET_ORDER_LOADING";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

// get orders
export const ORDER_DETAILS_LOADING = "ORDER_DETAILS_LOADING";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_ERROR = "ORDER_DETAILS_ERROR";

///////////    admin   ///////////////
// get all orders
export const GET_ALL_ORDERS_LOADING = "GET_ALL_ORDERS_LOADING";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR";

// delete orders
export const DELETE_ORDERS_SUCCESS = "DELETE_ORDERS_SUCCESS";
export const DELETE_ORDERS_ERROR = "DELETE_ORDERS_ERROR";
export const DELETE_ORDERS_RESET = "DELETE_ORDERS_RESET";

// update orders
export const UPDATE_ORDERS_LOADING = "UPDATE_ORDERS_LOADING";
export const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";
export const UPDATE_ORDERS_ERROR = "UPDATE_ORDERS_ERROR";
export const UPDATE_ORDERS_RESET = "UPDATE_ORDERS_RESET";
