///  all products
export const ALL_PRODUCTS_LOADING = "ALL_PRODUCTS_LOADING";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_ERROR = "ALL_PRODUCTS_ERROR";

///  single products
export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";

// add review
export const ADD_PRODUCT_REVIEW_LOADING = "ADD_PRODUCT_REVIEW_LOADING";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_ERROR = "ADD_PRODUCT_REVIEW_ERROR";

// categories
export const PRODUCT_CATEGORIES_SUCCESS = "PRODUCT_CATEGORIES_SUCCESS";
export const PRODUCT_CATEGORIES_ERROR = "ADD_PRODUCT_REVIEW_ERROR";
