///  all products
export const ALL_PRODUCTS_LOADING = "ALL_PRODUCTS_LOADING";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_ERROR = "ALL_PRODUCTS_ERROR";

///  single products
export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";

// add review
export const ADD_PRODUCT_REVIEW_LOADING = "ADD_PRODUCT_REVIEW_LOADING";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_ERROR = "ADD_PRODUCT_REVIEW_ERROR";

// categories
export const PRODUCT_CATEGORIES_SUCCESS = "PRODUCT_CATEGORIES_SUCCESS";
export const PRODUCT_CATEGORIES_ERROR = "ADD_PRODUCT_REVIEW_ERROR";

// clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";

////////////////////  Admin   ////////////////////////////
// get products
export const GET_ADMIN_PRODUCTS_LOADING = "GET_ADMIN_PRODUCTS_LOADING";
export const GET_ADMIN_PRODUCTS_SUCCESS = "GET_ADMIN_PRODUCTS_SUCCESS";
export const GET_ADMIN_PRODUCTS_ERROR = "GET_ADMIN_PRODUCTS_ERROR";

// create products
export const CREATE_ADMIN_PRODUCTS_LOADING = "CREATE_ADMIN_PRODUCTS_LOADING";
export const CREATE_ADMIN_PRODUCTS_SUCCESS = "CREATE_ADMIN_PRODUCTS_SUCCESS";
export const CREATE_ADMIN_PRODUCTS_ERROR = "CREATE_ADMIN_PRODUCTS_ERROR";
export const CREATE_ADMIN_PRODUCTS_RESET = "CREATE_ADMIN_PRODUCTS_RESET";

// update products
export const UPDATE_ADMIN_PRODUCTS_LOADING = "UPDATE_ADMIN_PRODUCTS_LOADING";
export const UPDATE_ADMIN_PRODUCTS_SUCCESS = "UPDATE_ADMIN_PRODUCTS_SUCCESS";
export const UPDATE_ADMIN_PRODUCTS_ERROR = "UPDATE_ADMIN_PRODUCTS_ERROR";
export const UPDATE_ADMIN_PRODUCTS_RESET = "UPDATE_ADMIN_PRODUCTS_RESET";

// delete products
export const DELETE_ADMIN_PRODUCTS_LOADING = "DELETE_ADMIN_PRODUCTS_LOADING";
export const DELETE_ADMIN_PRODUCTS_SUCCESS = "DELETE_ADMIN_PRODUCTS_SUCCESS";
export const DELETE_ADMIN_PRODUCTS_ERROR = "DELETE_ADMIN_PRODUCTS_ERROR";
export const DELETE_ADMIN_PRODUCTS_RESET = "DELETE_ADMIN_PRODUCTS_RESET";

// get all reviews
export const GET_ALL_PRODUCT_REVIEW_LOADING = "GET_ALL_PRODUCT_REVIEW_LOADING";
export const GET_ALL_PRODUCT_REVIEW_SUCCESS = "GET_ALL_PRODUCT_REVIEW_SUCCESS";
export const GET_ALL_PRODUCT_REVIEW_ERROR = "GET_ALL_PRODUCT_REVIEW_ERROR";

// delete review
export const DELETE_PRODUCT_REVIEW_LOADING = "DELETE_PRODUCT_REVIEW_LOADING";
export const DELETE_PRODUCT_REVIEW_SUCCESS = "DELETE_PRODUCT_REVIEW_SUCCESS";
export const DELETE_PRODUCT_REVIEW_ERROR = "DELETE_PRODUCT_REVIEW_ERROR";
export const DELETE_PRODUCT_REVIEW_RESET = "DELETE_PRODUCT_REVIEW_RESET";
